// Read/write Xilinx .xdc pin constraints for the pin planner.
// The planner owns PACKAGE_PIN/IOSTANDARD lines for board pins; every other
// line (comments, clocks, config properties, pins not on the board) is kept
// verbatim in a "manual" section at the end of the file.

import type { PinDef } from './boards/basys3-pins';

export interface XdcModel {
  /** board signal (e.g. "led[3]") -> design port bit (e.g. "leds[3]") */
  assign: Map<string, string>;
  /** lines the planner does not manage, kept as-is */
  manual: string[];
}

export const GENERATED_HEADER = '## Generated by the FPGA Web pin planner.';
export const MANUAL_MARKER = '## ---- manual constraints (kept as-is) ----';
const HEADER_LINES = [
  GENERATED_HEADER,
  '## Pin lines are re-read by the planner; edit them there or here.',
];

const GET_PORTS = /\[get_ports\s+(?:\{\s*([^}]*?)\s*\}|([^\s\]]+))\s*\]/;
const DICT = /set_property\s+-dict\s+\{([^}]*)\}/;
const SINGLE = /set_property\s+(PACKAGE_PIN|IOSTANDARD|PULLUP)\s+(\S+)/;

function portOf(line: string): string | null {
  const m = GET_PORTS.exec(line);
  const p = (m?.[1] ?? m?.[2] ?? '').trim();
  return p && !/\s/.test(p) ? p : null;
}

function packagePin(line: string): string | null {
  const d = DICT.exec(line);
  if (d) return /PACKAGE_PIN\s+(\S+)/.exec(d[1])?.[1] ?? null;
  const s = SINGLE.exec(line);
  return s && s[1] === 'PACKAGE_PIN' ? s[2] : null;
}

function isPinPropertyOnly(line: string): boolean {
  const d = DICT.exec(line);
  if (d) return d[1].trim().split(/\s+/).every((w, i) => (i % 2 === 0 ? /^(PACKAGE_PIN|IOSTANDARD|PULLUP)$/.test(w) : true));
  return SINGLE.test(line);
}

export function parseXdc(text: string, board: PinDef[]): XdcModel {
  const byPin = new Map(board.map((p) => [p.pin.toUpperCase(), p]));
  const assign = new Map<string, string>();
  const portPins = new Map<string, string>(); // port bit -> board signal (to absorb IOSTANDARD-only lines)
  const pending: string[] = [];

  const lines = text.replace(/\r\n?/g, '\n').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (HEADER_LINES.includes(trimmed) || trimmed === MANUAL_MARKER) continue;
    const port = trimmed.startsWith('#') ? null : portOf(trimmed);
    const pin = port ? packagePin(trimmed) : null;
    const def = pin ? byPin.get(pin.toUpperCase()) : undefined;
    if (port && def && isPinPropertyOnly(trimmed)) {
      assign.set(def.signal, port);
      portPins.set(port, def.signal);
      continue;
    }
    pending.push(line);
  }
  // Second pass: drop IOSTANDARD/PULLUP-only lines for ports the planner now owns.
  const manual = pending.filter((line) => {
    const t = line.trim();
    const port = t.startsWith('#') ? null : portOf(t);
    return !(port && portPins.has(port) && isPinPropertyOnly(t) && packagePin(t) === null);
  });
  while (manual.length && manual[manual.length - 1].trim() === '') manual.pop();
  while (manual.length && manual[0].trim() === '') manual.shift();
  return { assign, manual };
}

export function generateXdc(model: XdcModel, board: PinDef[]): string {
  const out = [...HEADER_LINES];
  for (const def of board) {
    const port = model.assign.get(def.signal);
    if (!port) continue;
    const props = `PACKAGE_PIN ${def.pin} IOSTANDARD ${def.iostandard}${def.pullup ? ' PULLUP true' : ''}`;
    out.push(`set_property -dict { ${props} } [get_ports { ${port} }]`);
  }
  if (model.manual.length) out.push('', MANUAL_MARKER, ...model.manual);
  return out.join('\n') + '\n';
}
